### ISSUE TITLE
Feature | Login from a directory other than a layer

### ISSUE THREAD

**Issue by juanmatias** [binbashar/leverage#189]
## Describe the Feature

As per one of our client users request, it is desirable to be able to log in with Leverage from any directory inside a Leverage project.

Today there is a requirement to be in a layer directory to login. The idea is to allow the user to run the login command for Leverage from any directory under the Leverage project.

As per this line the login can be done from account, layer o layer-group dirs:
https://github.com/binbashar/leverage/blob/master/leverage/modules/aws.py#L147

When configuring:
```shell
❯ leverage aws configure sso
[16:45:00.071] ERROR    SSO configuration can only be performed at layer level.
```
## Expected Behavior

To be able to log in from any directory under a project.

**Comment by exequielrafaela** [comment]
Adding extra comments based on @juanmatias and @diego-ojeda-binbash slack discussion.

- The user wants to avoid going to a layer of the reference architecture to refresh credentials and be able to use `kubectl`.
- An integration with `kubeconfig` would be needed - perhaps it could go hand in hand with the idea of @angelofenoglio / @Franr to create a script (a little independent and reusable) that handles credentials and other interactions with the AWS API via Boto.
- There are two things here... one is how to log in to AWS (e.g. `leverage aws sso login`) and the other is how we're getting the `kubectl` creds (which is in the new version of `leverage` CLI). 
   - For the first one, it's what I put in the ticket
   - For the second, you have to be in the cluster layer because of the outputs so some extra review and design will be needed.

CC: @binbashar/leverage-ref-architecture-aws-dev @binbashar/leverage-ref-architecture-aws-admin

**Comment by exequielrafaela** [comment]
Even if this could be seen as nice to have for a future version, for the moment we'll close this issue till customer projects actively requires it. This will give more space to work on more urgent fixes and features.

For the moment the user can get both AWS and Kubectl credentials using the leverage standard workflows
- https://leverage.binbash.co/user-guide/leverage-cli/reference/kubectl/#configure
- AWS SSO creds
   - https://leverage.binbash.co/user-guide/ref-architecture-aws/features/sso/configuration/#1-configuring-aws-sso
   - https://leverage.binbash.co/user-guide/leverage-cli/reference/aws/
   - https://gist.github.com/exequielrafaela/2d963c6f12186a1492f870ce2f9f9dde
