### ISSUE TITLE
"aws sso login" stuck when CLI is not able to open the browser

### ISSUE THREAD

**Issue by Franr** [binbashar/leverage#196]
## Describe the Bug
If you run `leverage aws sso login` from [WSL](https://learn.microsoft.com/en-us/windows/wsl/), the webbrowser lib [is not able](https://github.com/python/cpython/issues/89752) to open browsers yet.

## Expected Behavior
So we need to provide an automatic way (and a flag) of falling back to the previous behavior of printing the URL with the code
and let the user handle it by themselves.
Also, once the [bug is fixed](https://github.com/python/cpython/issues/89752), the automatic fallback should be removed.

## Steps to Reproduce
1. Go to any layer of a project.
2. Run `leverage aws sso login`
3. The command will hang waiting the browser to be opened.

## Screenshots
![image](https://user-images.githubusercontent.com/482506/234901054-b19ddfe7-c629-456f-ad6f-924b10596a24.png)

## Environment:
```
>> uname -r
5.15.90.1-microsoft-standard-WSL2
```

**Comment by angelofenoglio** [comment]
This issue seems to provide a good workaround using wslview to launch the browser form within WSL: https://github.com/python/cpython/issues/89752. I think it's worth a try.

Also https://docs.python.org/3/library/platform.html?highlight=platform#platform.uname would be the python native version of `uname `

**Comment by Franr** [comment]
Resolved here: https://github.com/binbashar/leverage/pull/203
